spring.application.name=uberApp

#DB configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST_URL}:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

#Security Config
jwt.secretKey = ${JWT_SECRET_KEY}

#SMTP Config
spring.mail.username=
spring.mail.password=
spring.mail.host=
spring.mail.port=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
